### PR TITLE
if not dev, dont build changelog

### PR DESCRIPTION
**Pull request by nabobalis**
Update for changelog from sunpy master.

### CODE REVIEW

**Comment by Cadair** [comment]
We should also pull this into ndcube. Also we should get the template to the point where we can retemplate things for these kind of changes.

**Comment by nabobalis** [comment]
IF ONLY SOMEONE WOULD MERGE IN MY PR FOR NDCUBE

**Comment by nabobalis** [comment]
IF ONLY MY PR COULD BE MERGED IN SO I COULD LEAVE THE ROOM

**Comment by nabobalis** [comment]
IM NOT MAD IM JUST ANGRY

**Pull request merged**
