### PR TITLE
Upgrade ASDA to version 2.1

### PR DESCRIPTION
**Pull request by PyDL**
Add new function get_vortex() in asda.py, new functions read_vortex() and save_vortex() in utils.py

### CODE REVIEW

**Comment by nabobalis** [comment]
Hi @PyDL, thanks for the PR.

I will review it soon but what does the new version of ASDA do?

**Comment by PyDL** [comment]
Hi @nabobalis ,

I added some handy functions to ASDA in version 2.1. 

In asda.py, a new function self.get_vortex() is added to the ASDA class. Calling this function will perform the vortex detection by executing self.gamma_values(), self.center_edge() and self.vortex_property(). Some if conditions are also added in the above three functions, to avoid the calculations being done again if these functions have been called already. Accordingly, test_asda.py has also been updated.

In utils.py, two new functions read_vortex() and save_vortex() are added. They allow people to read/save vortex detection results into files with npz or h5 formats.

The core algorithm of ASDA keeps unchanged.

**Comment by nabobalis** [comment]
Where is ASDA 2.1 defined?

Are you happy with me making the changes needed for the tests and things to pass or do you want to have a go?

**Comment by PyDL** [comment]
Hi @nabobalis sorry I forgot to define in the code it's ASDA 2.1

I would be grateful if you could make the changes needed. Thank you.

**Pull request closed without merging**
