### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by nabobalis**
=

### CODE REVIEW

**Comment by ConorMacBride** [comment]
The issue with installing tox-conda on windows is fixed but there's another issue with the build system dependencies: https://dev.azure.com/sunpy/sunkit-image/_build/results?buildId=23480&view=logs&j=c250cb2b-914a-5305-03b5-eac06df8f1e7&t=1dccccf3-3c22-5ad3-d0d5-caa56ea5243f

Maybe `extension_helpers` needs to be in the conda-forge recipe or maybe added to [`toxdeps`](https://openastronomy-azure-pipelines.readthedocs.io/en/latest/run_tox_env.html#pre-tox-python-dependencies).

**Comment by nabobalis** [comment]
> The issue with installing tox-conda on windows is fixed but there's another issue with the build system dependencies: https://dev.azure.com/sunpy/sunkit-image/_build/results?buildId=23480&view=logs&j=c250cb2b-914a-5305-03b5-eac06df8f1e7&t=1dccccf3-3c22-5ad3-d0d5-caa56ea5243f

Thanks for fixing it.

> Maybe `extension-helpers` needs to be in the conda-forge recipe or maybe added to [`toxdeps`](https://openastronomy-azure-pipelines.readthedocs.io/en/latest/run_tox_env.html#pre-tox-python-dependencies).

Yeah it is missing from the tox deps in tox.ini.

**Comment by nabobalis** [comment]
That didn't fix it.

**Comment by ConorMacBride** [comment]
The conda test runs fine on macOS locally but I don't have a Windows machine to test on. While it would be good to know why it doesn't work on Windows, just change to linux? [Everyone else who uses this template](https://cs.github.com/?scopeName=All+repos&scope=&q=path%3Aazure-pipelines.yml+%22OpenAstronomy%2Fazure-pipelines-templates%22+%22conda%22) only runs the conda test on macOS or Linux so no working example to compare to.

**Comment by nabobalis** [comment]
> The conda test runs fine on macOS locally but I don't have a Windows machine to test on. While it would be good to know why it doesn't work on Windows, just change to linux? [Everyone else who uses this template](https://cs.github.com/?scopeName=All+repos&scope=&q=path%3Aazure-pipelines.yml+%22OpenAstronomy%2Fazure-pipelines-templates%22+%22conda%22) only runs the conda test on macOS or Linux so no working example to compare to.

That is fair but I hit an issue on the conda feedstock PR on the windows build only that I wanted to try and replicate here.

**Comment by nabobalis** [comment]
I might skip the test that failed on windows.

**Pull request merged**
