### PR TITLE
Add ASDA into sunkit-image

### PR DESCRIPTION
**Pull request by PyDL**
Add ASDA into sunkit-image

### Description

First attempt to integrate ASDA into sunkit-image

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks @PyDL, I will go through it and probably update it to follow our coding standards! I'll try to get it in for the next release.

**Comment by PyDL** [comment]
> Thanks @PyDL, I will go through it and probably update it to follow our coding standards! I'll try to get it in for the next release.

@nabobalis Thank you. Please let me know if anything is needed.

**Comment by nabobalis** [comment]
I'll get onto this on Saturday

**Comment by nabobalis** [comment]
@PyDL I havn't finished (need to do the tests and example next) but you can see the changes I have made to the main ASDA code in the last commit. 

I have just moved some things around and tidied up the code otherwise nothing has changed.

**Comment by nabobalis** [comment]
I've changed the tests to check for values, now I just need to get the example to be functional.

**Comment by nabobalis** [comment]
Thanks @PyDL

**Pull request merged**
